name: deploy-curriculum-vitae
on:
  push:
    branches:
      - main
jobs:
  deploy-to-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
         
      - name: Copy to ./dist
        run: mkdir dist && cp index.html dist/

      - name: Deploy
        uses: nwtgck/actions-netlify@v2.0
        with:
           publish-dir: './dist'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
       
          